# Generated by Django 5.2.4 on 2026-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcomplianceitem',
            name='kanban_status',
            field=models.CharField(choices=[('nao_conforme', 'Não Conforme'), ('em_preparo', 'Em Preparo'), ('concluido', 'Concluído')], db_index=True, default='nao_conforme', max_length=20),
        ),
        migrations.AddField(
            model_name='shiftcomplianceitem',
            name='kanban_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
