# Generated by Django 5.2.4 on 2026-02-26 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0002_shiftcomplianceitem_kanban_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('area_servico', models.CharField(choices=[('limpeza', 'Serviços de Limpeza'), ('entreposto', 'Serviços de Entreposto'), ('coffe', 'Serviços de Coffe')], max_length=50, verbose_name='Área de Serviço')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prestador de Serviço',
                'db_table': 'prestador_servico',
            },
        ),
        migrations.AddField(
            model_name='gestaosala',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='salas_fotos/'),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='servico_coffe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='servico_entreposto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='servico_limpeza',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='LivroOcorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cr', models.CharField(db_index=True, max_length=100, verbose_name='CR')),
                ('solicitante', models.CharField(db_index=True, max_length=255, verbose_name='Solicitante')),
                ('item', models.CharField(db_index=True, max_length=255, verbose_name='Item')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('NC', 'Não Conforme'), ('AND', 'Em Andamento'), ('C', 'Conforme')], default='NC', max_length=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Livro de Ocorrências',
                'db_table': 'Gestao_a_Vista_livroocorrencia',
                'indexes': [models.Index(fields=['cr', 'solicitante', 'item'], name='Gestao_a_Vi_cr_428bbe_idx')],
            },
        ),
    ]
