# Generated by Django 5.2.4 on 2026-02-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0003_prestadorservico_gestaosala_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAcaoTorre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, verbose_name='Item')),
                ('colaborador_cr', models.CharField(max_length=255, verbose_name='Colaborador / CR')),
                ('tem_estoque', models.BooleanField(default=True, verbose_name='Tem no Estoque?')),
                ('descricao', models.TextField(verbose_name='Descrição / Ação a ser tomada')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado pelo Coordenador')], default='em_andamento', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano de Ação (Torre)',
                'verbose_name_plural': 'Planos de Ação (Torre)',
                'db_table': 'plano_acao_torre',
                'ordering': ['-created_at'],
            },
        ),
    ]
