# Generated by Django 5.2.4 on 2026-02-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0004_planoacaotorre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmailTorre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr', models.CharField(help_text="Nome do CR ou digite 'GERAL' para um contato padrão.", max_length=100, unique=True, verbose_name='CR / Unidade')),
                ('nome_gerente', models.CharField(max_length=100, verbose_name='Nome do Gerente')),
                ('email_gerente', models.EmailField(max_length=254, verbose_name='E-mail do Gerente')),
                ('nome_coordenador', models.CharField(max_length=100, verbose_name='Nome do Coordenador')),
                ('email_coordenador', models.EmailField(max_length=254, verbose_name='E-mail do Coordenador')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail (Torre)',
                'verbose_name_plural': 'Configurações de E-mails (Torre)',
                'db_table': 'configuracao_email_torre',
            },
        ),
        migrations.AlterField(
            model_name='planoacaotorre',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado pelo Coordenador'), ('rejeitado', 'Rejeitado pelo Coordenador')], default='em_andamento', max_length=30, verbose_name='Status'),
        ),
    ]
