# Generated by Django 5.2.4 on 2026-03-01 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0005_configuracaoemailtorre_alter_planoacaotorre_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaPlanoAcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_em_falta', models.CharField(max_length=255, verbose_name='Item em Falta')),
                ('colaborador_nc', models.CharField(max_length=255, verbose_name='Colaborador (NC)')),
                ('cr_colaborador', models.CharField(max_length=100, verbose_name='CR do Colaborador')),
                ('tem_estoque', models.BooleanField(default=False, verbose_name='Tem no Estoque?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('em_aprovacao', 'Em Aprovação'), ('compra_cadastrar', 'Compra - A Cadastrar'), ('compra_pedido', 'Compra - Pedido Realizado'), ('compra_entregue', 'Compra - Entregue (Aguardando Retirada)'), ('concluido', 'Concluído'), ('rejeitado', 'Rejeitado')], default='em_aprovacao', max_length=30, verbose_name='Status')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('itens_compra', models.JSONField(blank=True, default=list, verbose_name='Itens da Compra')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='notas_fiscais_ocorrencia/', verbose_name='Nota Fiscal')),
                ('recebedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Recebedor')),
                ('item_retirado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Retirado')),
                ('data_retirada', models.DateTimeField(blank=True, null=True, verbose_name='Data da Retirada')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ocorrencia_aprovados', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ocorrencia_comprados', to=settings.AUTH_USER_MODEL)),
                ('criador_plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ocorrencia_criados', to=settings.AUTH_USER_MODEL)),
                ('retirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ocorrencia_retirados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Ação da Ocorrência',
                'verbose_name_plural': 'Planos de Ação das Ocorrências',
                'db_table': 'ocorrencia_plano_acao',
                'ordering': ['-data_criacao'],
            },
        ),
        
    ]
