# Generated by Django 5.2.4 on 2026-03-01 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0006_ocorrenciaplanoacao_delete_planoacaotorre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ocorrencia_excluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrenciaplanoacao',
            name='status',
            field=models.CharField(choices=[('em_aprovacao', 'Em Aprovação'), ('compra_cadastrar', 'Compra - A Cadastrar'), ('compra_pedido', 'Compra - Pedido Realizado'), ('compra_entregue', 'Compra - Entregue (Aguardando Retirada)'), ('concluido', 'Concluído'), ('rejeitado', 'Rejeitado'), ('excluido', 'Excluído')], default='em_aprovacao', max_length=30, verbose_name='Status'),
        ),
    ]
