# Generated by Django 5.2.4 on 2026-03-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0007_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGerenteOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Gerente')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Gerente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Receber Notificações')),
            ],
            options={
                'verbose_name': 'E-mail de Gerente (Ocorrências)',
                'verbose_name_plural': 'E-mails de Gerentes (Ocorrências)',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoEmailTorre',
        ),
    ]
