# Generated by Django 5.2.4 on 2026-03-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0008_emailgerenteocorrencia_delete_configuracaoemailtorre_and_more'),
    ]

