# Generated by Django 5.2.4 on 2026-03-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0009_delete_planoacaotorre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
    ]
