# Generated by Django 5.2.4 on 2026-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0010_delete_planoacaotorre_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='foto_retirada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_retirada_ocorrencia/', verbose_name='Foto da Retirada'),
        ),
    ]
