# Generated by Django 5.2.4 on 2026-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0011_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCompradorOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Comprador')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Comprador')),
                ('ativo', models.BooleanField(default=True, verbose_name='Receber Alertas de Atraso')),
            ],
            options={
                'verbose_name': 'E-mail de Comprador (Ocorrências)',
                'verbose_name_plural': 'E-mails de Compradores (Ocorrências)',
            },
        ),
    ]
