# Generated by Django 5.2.4 on 2026-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0011_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='justificativa_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Aprovação/Rejeição'),
        ),
    ]
