# Generated by Django 5.2.4 on 2026-03-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0012_delete_planoacaotorre_and_more'),
        ('Gestao_a_Vista', '0012_emailcompradorocorrencia_delete_planoacaotorre'),
    ]

    operations = [
    ]
