# Generated by Django 5.2.4 on 2026-03-12 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0013_merge_20260312_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReincidenciaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_colaborador', models.CharField(max_length=255)),
                ('item_reincidente', models.CharField(max_length=255)),
                ('coordenador', models.CharField(blank=True, max_length=255, null=True)),
                ('gerente', models.CharField(blank=True, max_length=255, null=True)),
                ('data_reincidencia', models.DateTimeField(auto_now_add=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=50)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plano_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reincidencias', to='Gestao_a_Vista.ocorrenciaplanoacao')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailCompradorOcorrencia',
        ),
    ]
