# Generated by Django 5.2.4 on 2026-03-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0014_reincidenciaocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailgerenteocorrencia',
            options={},
        ),
        migrations.RemoveField(
            model_name='emailgerenteocorrencia',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='emailgerenteocorrencia',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailgerenteocorrencia',
            name='nome',
        ),
        migrations.AddField(
            model_name='emailgerenteocorrencia',
            name='cr',
            field=models.CharField(default='GERAL', max_length=255, verbose_name='CR (Centro de Resultado)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailgerenteocorrencia',
            name='email_coordenador',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Coordenador'),
        ),
        migrations.AddField(
            model_name='emailgerenteocorrencia',
            name='email_gerente',
            field=models.EmailField(default='GERAL', max_length=254, verbose_name='E-mail do Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailgerenteocorrencia',
            name='nome_coordenador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Coordenador'),
        ),
        migrations.AddField(
            model_name='emailgerenteocorrencia',
            name='nome_gerente',
            field=models.CharField(default='GERAL', max_length=255, verbose_name='Nome do Gerente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('publico', 'Público'), ('cliente', 'Cliente')], default='publico', max_length=20),
        ),
    ]
