# Generated by Django 5.2.4 on 2026-03-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0015_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailgerenteocorrencia',
            name='cr',
        ),
    ]
