# Generated by Django 5.2.4 on 2026-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0016_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='crs',
            field=models.TextField(blank=True, help_text='Ex: CR 01, CR 02. Deixe em branco se for Geral.', verbose_name='CRs (separados por vírgula)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_general',
            field=models.BooleanField(default=False, verbose_name='Recebe de todos os CRs? (Geral)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_regulatory',
            field=models.BooleanField(default=False, verbose_name='É do Regulatório?'),
        ),
        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='is_regulatory',
            field=models.BooleanField(default=False, verbose_name='É Regulatório?'),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='is_regulatory',
            field=models.BooleanField(default=False, verbose_name='É Regulatório?'),
        ),
    ]
