# Generated by Django 5.2.4 on 2026-03-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0017_delete_planoacaotorre_customuser_crs_and_more'),
    ]

