# Generated by Django 5.2.4 on 2026-03-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0018_delete_planoacaotorre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGerenteOcorrencia',
        ),

    ]
