# Generated by Django 5.2.4 on 2026-03-16 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0019_delete_emailgerenteocorrencia_delete_planoacaotorre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaOcorrenciaStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocorrencia_hash', models.CharField(db_index=True, help_text='Identificador único: estrutura_id|item|data', max_length=512, unique=True, verbose_name='Hash da Ocorrência')),
                ('auditado_em', models.DateTimeField(auto_now_add=True, verbose_name='Auditado em')),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por')),
            ],
            options={
                'verbose_name': 'Status de Auditoria',
                'verbose_name_plural': 'Status de Auditorias',
                'db_table': 'auditoria_ocorrencia_status',
                'ordering': ['-auditado_em'],
            },
        ),
    ]
