# Generated by Django 5.2.4 on 2026-03-16 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0020_auditoria_ocorrencia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaocorrenciastatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditoriaocorrenciastatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='auditado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='auditado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='ocorrencia_hash',
            field=models.CharField(help_text='Hash único da ocorrência (ID + Item)', max_length=255, primary_key=True, serialize=False),
        ),
    ]
