# Generated by Django 5.2.4 on 2026-03-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestao_a_Vista", "0021_delete_planoacaotorre_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ocorrenciaplanoacao",
            index=models.Index(
                fields=["status", "cr_colaborador"], name="ocorrencia_status_cr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocorrenciaplanoacao",
            index=models.Index(
                fields=["cr_colaborador", "item_em_falta"],
                name="ocorrencia_cr_item_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ocorrenciaplanoacao",
            index=models.Index(
                fields=["-data_criacao", "status"], name="ocorrencia_criacao_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservasala",
            index=models.Index(
                fields=["sala_id", "data"], name="reservasala_sala_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservasala",
            index=models.Index(
                fields=["data", "status"], name="reservasala_data_status_idx"
            ),
        ),
    ]
