# Generated by Django 5.2.4 on 2026-03-19 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0022_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='estrutura_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='image_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='is_coincidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='tratada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='tratada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='tratada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coincidencias_tratadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='auditado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='auditado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoriaocorrenciastatus',
            name='ocorrencia_hash',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
