# Generated by Django 5.2.4 on 2026-03-23 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0023_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPlanoAcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('status_novo', models.CharField(max_length=50)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_plano_acao',
                'ordering': ['data_alteracao'],
            },
        ),
        # Removed conflicting auditoriaocorrenciastatus operations
        migrations.AddField(
            model_name='ocorrenciaplanoacao',
            name='guia_de_trafego',
            field=models.FileField(blank=True, null=True, upload_to='guias_trafego_ocorrencia/', verbose_name='Guia de Tráfego'),
        ),
        migrations.AddField(
            model_name='historicoplanoacao',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='Gestao_a_Vista.ocorrenciaplanoacao'),
        ),
        migrations.AddField(
            model_name='historicoplanoacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
