# Generated by Django 5.2.4 on 2026-04-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0024_historicoplanoacao_delete_planoacaotorre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanoAcaoTorre',
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='colaborador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='cr_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='data_ocorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='evidencia_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestadores', to='Gestao_a_Vista.unidade', verbose_name='Unidade / Local'),
        ),
    ]
