# Generated by Django 5.2.4 on 2026-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0025_add_unidade_to_prestadorservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reincidenciaocorrencia',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reincidenciaocorrencia',
            name='justificativa_auditoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reincidenciaocorrencia',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
