# Generated by Django 5.2.4 on 2026-05-27 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0028_cardimplantacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('OPEN', 'Abertura'), ('EDIT', 'Edição'), ('RENAME', 'Renomeação'), ('DELETE', 'Exclusão')], max_length=20, verbose_name='Ação')),
                ('node_name', models.CharField(max_length=255, verbose_name='Nome do Item')),
                ('node_type', models.CharField(choices=[('folder', 'Pasta'), ('file', 'Arquivo')], max_length=10, verbose_name='Tipo do Item')),
                ('details', models.TextField(blank=True, verbose_name='Detalhes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('user_name', models.CharField(default='Desconhecido', max_length=255, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria do Explorer',
                'verbose_name_plural': 'Auditoria do Explorer',
                'db_table': 'Gestao_a_Vista_explorerauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExplorerNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_folder', models.BooleanField(default=False, verbose_name='É pasta?')),
                ('content', models.TextField(blank=True, default='', verbose_name='Conteúdo')),
                ('file_type', models.CharField(choices=[('text', 'Texto Normal'), ('code', 'Código')], default='text', max_length=20, verbose_name='Tipo de Arquivo')),
                ('language', models.CharField(blank=True, default='plain', help_text='Linguagem de programação para syntax highlighting se for código (ex: html, javascript, python, css)', max_length=50, verbose_name='Linguagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by_name', models.CharField(default='Sistema', max_length=255, verbose_name='Criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Gestao_a_Vista.explorernode', verbose_name='Pasta Pai')),
            ],
            options={
                'verbose_name': 'Nó do Explorer',
                'verbose_name_plural': 'Nós do Explorer',
                'db_table': 'Gestao_a_Vista_explorernode',
                'ordering': ['is_folder', 'name'],
            },
        ),
    ]
