# Generated by Django 5.2.4 on 2026-06-02 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0029_livroocorrencia_numero_explorerauditlog_explorernode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDesmobilizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cr', models.CharField(db_index=True, max_length=100, verbose_name='CR')),
                ('cr_descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição do CR')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], db_index=True, default='em_andamento', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Desmobilização de CR',
                'verbose_name_plural': 'Desmobilizações de CR',
                'db_table': 'Gestao_a_Vista_carddesmobilizacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='setor',
            field=models.CharField(blank=True, choices=[('TI', 'TI'), ('PEC', 'PEC'), ('QUALIDADE', 'Qualidade'), ('PROJETOS', 'Projetos'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'Suprimentos'), ('BI', 'BI')], db_index=True, max_length=20, null=True, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('supervisor', 'Supervisor'), ('publico', 'Público'), ('cliente', 'Cliente')], default='publico', max_length=20),
        ),
        migrations.CreateModel(
            name='DesmobilizacaoPerguntaResposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(db_index=True, max_length=20, verbose_name='Área')),
                ('pergunta_key', models.CharField(max_length=50, verbose_name='Chave da Pergunta')),
                ('texto_pergunta', models.TextField(verbose_name='Texto da Pergunta')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('resposta_texto', models.TextField(blank=True, null=True, verbose_name='Resposta/Observação')),
                ('respondido_por_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Respondido por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='Gestao_a_Vista.carddesmobilizacao')),
            ],
            options={
                'verbose_name': 'Resposta de Desmobilização',
                'verbose_name_plural': 'Respostas de Desmobilização',
                'db_table': 'Gestao_a_Vista_desmobilizacaoperguntaresposta',
                'ordering': ['area', 'pergunta_key'],
            },
        ),
        migrations.CreateModel(
            name='DesmobilizacaoAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='desmobilizacoes/anexos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('pergunta_resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Gestao_a_Vista.desmobilizacaoperguntaresposta')),
            ],
            options={
                'verbose_name': 'Anexo de Desmobilização',
                'verbose_name_plural': 'Anexos de Desmobilização',
                'db_table': 'Gestao_a_Vista_desmobilizacaoanexo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
