# Generated by Django 5.2.4 on 2026-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0030_carddesmobilizacao_customuser_setor_and_more'),
    ]

    operations = [
    ]
