# Generated by Django 5.2.4 on 2026-06-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0031_livroocorrencia_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesmobilizacao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desmobilizacoes_criadas', to='Gestao_a_Vista.customuser', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implantacoes_criadas', to='Gestao_a_Vista.customuser', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step2_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 2 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step3_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 3 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step4_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 4 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step5_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 5 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step6_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 6 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step7_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 7 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step8_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 8 concluída em'),
        ),
        migrations.AddField(
            model_name='cardimplantacao',
            name='step9_concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etapa 9 concluída em'),
        ),
    ]
