# Generated by Django 5.2.4 on 2026-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0032_card_created_by_and_step_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroocorrencia',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Tarefa'),
        ),
    ]
