# Generated by Django 5.2.4 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0033_livroocorrencia_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesmobilizacao',
            name='data_desmobilizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Solicitação'),
        ),
    ]
