# Generated by Django 5.2.4 on 2026-06-16 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0034_carddesmobilizacao_data_desmobilizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorSRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('negocio', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_demissao', models.DateField(blank=True, null=True)),
                ('cr', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador SRA',
                'verbose_name_plural': 'Colaboradores SRA',
                'db_table': 'Gestao_a_Vista_colaboradorsra',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='setor',
            field=models.CharField(blank=True, choices=[('TI', 'TI'), ('PEC', 'PEC/ FINANCEIRO'), ('QUALIDADE', 'Qualidade'), ('PROJETOS', 'Projetos'), ('SESMT', 'SESMT'), ('SUPRIMENTOS', 'Suprimentos'), ('BI', 'BI')], db_index=True, max_length=20, null=True, verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='PsicossocialProjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto/Contrato')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True, verbose_name='CNPJ')),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade - UF')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Período Início')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Período Fim')),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Técnico')),
                ('data_aplicacao', models.DateField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planilha_respostas', models.FileField(upload_to='psicossocial/uploads/')),
                ('planilha_workforce', models.FileField(blank=True, null=True, upload_to='psicossocial/uploads/')),
                ('planilha_resultado', models.FileField(blank=True, null=True, upload_to='psicossocial/resultados/')),
                ('relatorio_word', models.FileField(blank=True, null=True, upload_to='psicossocial/resultados/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto Psicossocial',
                'verbose_name_plural': 'Projetos Psicossocial',
                'db_table': 'Gestao_a_Vista_psicossocialprojeto',
                'ordering': ['-created_at'],
            },
        ),
    ]
