# Generated by Django 5.2.4 on 2026-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0035_colaboradorsra_alter_customuser_setor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='colaboradores_sra',
            field=models.ManyToManyField(blank=True, to='Gestao_a_Vista.colaboradorsra'),
        ),
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='sra_cliente_filtro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='sra_tipo_selecao',
            field=models.CharField(default='todos', max_length=50),
        ),
    ]
