# Generated by Django 5.2.4 on 2026-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0036_psicossocialprojeto_colaboradores_sra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorsra',
            name='situacao',
            field=models.CharField(blank=True, default='Ativo', max_length=100, null=True),
        ),
    ]
