# Generated by Django 5.2.4 on 2026-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0037_colaboradorsra_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorsra',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorsra',
            name='empresa_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorsra',
            name='empresa_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorsra',
            name='filial_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorsra',
            name='grupo_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorsra',
            name='nome_unidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='empresa_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Empresa'),
        ),
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='filial_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Filial'),
        ),
        migrations.AlterField(
            model_name='psicossocialprojeto',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Técnico SSMA'),
        ),
    ]
