# Generated by Django 5.2.4 on 2026-06-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0038_colaboradorsra_cnpj_colaboradorsra_empresa_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicossocialprojeto',
            name='sra_unidade_filtro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
