# Generated by Django 5.2.4 on 2026-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0045_alter_psicossocialprojeto_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notificar_livro_ata',
            field=models.BooleanField(default=False, verbose_name='Recebe notificação de Livro Ata pendente (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_notificacao',
            field=models.CharField(blank=True, help_text='Ex: 5562999999999 (com DDI e DDD)', max_length=20, verbose_name='WhatsApp para notificação'),
        ),
    ]
