# Generated by Django 5.2.4 on 2026-06-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0049_planner_stage_context_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerproject',
            name='canal_relacionamento',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('reuniao', 'Reunião'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('chamado', 'Chamado / Service Desk'), ('presencial', 'Presencial'), ('outro', 'Outro')], default='', max_length=30, verbose_name='canal de relacionamento'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='crm_tipo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('analitico_360', 'Analítico / Visão 360º'), ('colaborativo', 'Colaborativo')], db_index=True, default='operacional', max_length=30, verbose_name='tipo de CRM'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='departamentos_envolvidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='departamentos envolvidos'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='proxima_interacao',
            field=models.DateField(blank=True, null=True, verbose_name='próxima interação'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='resumo_colaborativo',
            field=models.TextField(blank=True, null=True, verbose_name='resumo colaborativo'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='saude_relacionamento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='saúde do relacionamento'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='stakeholders',
            field=models.TextField(blank=True, null=True, verbose_name='stakeholders e papéis'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='ultima_interacao',
            field=models.DateField(blank=True, null=True, verbose_name='última interação'),
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='visao_360',
            field=models.TextField(blank=True, null=True, verbose_name='visão 360º do cliente/demanda'),
        ),
    ]
