# Generated by Django 5.2.4 on 2026-07-04 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_STAGES = [
    ("Entrada / Backlog", "#2563eb", 10),
    ("Triagem", "#7c3aed", 20),
    ("Planejamento 5W2H", "#0891b2", 30),
    ("Em Execução", "#f59e0b", 40),
    ("Aguardando Terceiros / Cliente", "#ea580c", 50),
    ("Validação / Testes", "#4f46e5", 60),
    ("Concluído", "#16a34a", 70),
    ("Cancelado / Suspenso", "#64748b", 80),
]


def create_default_stages(apps, schema_editor):
    Stage = apps.get_model('Gestao_a_Vista', 'PlannerPipelineStage')
    Project = apps.get_model('Gestao_a_Vista', 'PlannerProject')
    stage_by_status = {}
    for nome, cor, ordem in DEFAULT_STAGES:
        stage, _ = Stage.objects.get_or_create(
            nome=nome,
            defaults={'cor': cor, 'ordem': ordem, 'ativo': True, 'status_legado': nome},
        )
        stage_by_status[nome] = stage
    for projeto in Project.objects.filter(etapa__isnull=True).only('id', 'status', 'etapa'):
        stage = stage_by_status.get(projeto.status) or stage_by_status.get('Entrada / Backlog')
        projeto.etapa = stage
        projeto.save(update_fields=['etapa'])


def reverse_default_stages(apps, schema_editor):
    Stage = apps.get_model('Gestao_a_Vista', 'PlannerPipelineStage')
    Stage.objects.filter(nome__in=[nome for nome, _cor, _ordem in DEFAULT_STAGES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0050_planner_crm_profissional_360'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerproject',
            name='status',
            field=models.CharField(choices=[('Entrada / Backlog', 'Entrada / Backlog'), ('Triagem', 'Triagem'), ('Planejamento 5W2H', 'Planejamento 5W2H'), ('Em Execução', 'Em Execução'), ('Aguardando Terceiros / Cliente', 'Aguardando Terceiros / Cliente'), ('Validação / Testes', 'Validação / Testes'), ('Concluído', 'Concluído'), ('Cancelado / Suspenso', 'Cancelado / Suspenso')], db_index=True, default='Entrada / Backlog', max_length=80, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='PlannerPipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome da etapa')),
                ('cor', models.CharField(default='#2563eb', max_length=20, verbose_name='cor')),
                ('ordem', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('status_legado', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='status legado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Etapa do pipeline CRM',
                'verbose_name_plural': 'Etapas do pipeline CRM',
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['ativo', 'ordem'], name='planner_stage_active_order_idx')],
            },
        ),
        migrations.AddField(
            model_name='plannerproject',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='Gestao_a_Vista.plannerpipelinestage', verbose_name='etapa do pipeline'),
        ),
        migrations.AddIndex(
            model_name='plannerproject',
            index=models.Index(fields=['etapa', 'data_conclusao'], name='planner_etapa_conclusao_idx'),
        ),
        migrations.RunPython(create_default_stages, reverse_default_stages),
    ]
