# Generated by Django 5.2.4 on 2026-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0052_psicossocialprojeto_total_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditoriaocorrenciastatus',
            name='tarefa_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
