# Generated by Django 5.2.4 on 2026-07-09 17:22

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0056_solicitacaocadastro_regional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMOEfetivoConformidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(db_index=True, max_length=255, verbose_name='Cliente')),
                ('grupo_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Cliente')),
                ('cr', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CR')),
                ('tipo_servico_nome', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo de Serviço')),
                ('colaborador_nome', models.CharField(max_length=255, verbose_name='Colaborador')),
                ('colaborador_matricula', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('colaborador_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_referencia', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Data de Referência')),
                ('status_efetivo', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não Conforme')], max_length=20, verbose_name='Status do Efetivo')),
                ('motivo_nao_conformidade', models.CharField(blank=True, choices=[('falta_nao_justificada', 'Falta não justificada'), ('falta_justificada', 'Falta justificada'), ('atraso', 'Atraso'), ('atestado_medico', 'Atestado médico'), ('ferias', 'Férias'), ('afastamento', 'Afastamento'), ('abandono_posto', 'Abandono de posto'), ('outro', 'Outro')], max_length=30, null=True, verbose_name='Motivo da Não Conformidade')),
                ('motivo_outro_detalhe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhe (quando motivo = Outro)')),
                ('previsao_cobertura', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Cobertura')),
                ('impacto_folha', models.BooleanField(default=False, verbose_name='Tem impacto em ponto/folha?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_lancamento', models.CharField(choices=[('nao_aplica', 'Não se aplica'), ('pendente', 'Pendente de Lançamento'), ('lancado', 'Lançado em Folha')], db_index=True, default='nao_aplica', max_length=20, verbose_name='Status do Lançamento (CMO)')),
                ('cancelado', models.BooleanField(db_index=True, default=False)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_efetivo_canceladas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_efetivo_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_efetivo_contato', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Contato')),
            ],
            options={
                'verbose_name': 'Conformidade de Efetivo',
                'verbose_name_plural': 'Conformidades de Efetivo',
                'db_table': 'cmo_efetivo_conformidade',
                'ordering': ['-data_referencia', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='CMOEfetivoCobertura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_cobertura', models.CharField(max_length=255, verbose_name='Colaborador da Cobertura')),
                ('matricula_cobertura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('cliente_nome', models.CharField(db_index=True, max_length=255, verbose_name='Cliente')),
                ('grupo_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Cliente')),
                ('cr', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CR')),
                ('tipo_servico_nome', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo de Serviço')),
                ('colaborador_substituido', models.CharField(max_length=255, verbose_name='Colaborador Substituído')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_cobertura', models.DateField(db_index=True, verbose_name='Data da Cobertura')),
                ('horario_previsto', models.TimeField(blank=True, null=True, verbose_name='Horário Previsto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('nao_realizada', 'Não Realizada'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas_efetivo_criadas', to=settings.AUTH_USER_MODEL)),
                ('conformidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas', to='Gestao_a_Vista.cmoefetivoconformidade', verbose_name='Não Conformidade de Origem')),
            ],
            options={
                'verbose_name': 'Cobertura de Efetivo',
                'verbose_name_plural': 'Coberturas de Efetivo',
                'db_table': 'cmo_efetivo_cobertura',
                'ordering': ['-data_cobertura', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CMOEfetivoLancamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocorrencia_tipo', models.CharField(choices=[('conformidade', 'Conformidade de Efetivo'), ('cobertura', 'Cobertura'), ('troca', 'Troca de Serviço'), ('ajuste', 'Ajuste Manual')], max_length=20, verbose_name='Tipo de Ocorrência')),
                ('ocorrencia_id', models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='ID da Ocorrência de Origem')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Cliente')),
                ('colaborador_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colaborador')),
                ('lancado', models.BooleanField(db_index=True, default=False, verbose_name='Lançado em Folha?')),
                ('data_lancamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Lançamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel_cmo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_cmo_efetivo', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (CMO)')),
            ],
            options={
                'verbose_name': 'Lançamento CMO',
                'verbose_name_plural': 'Lançamentos CMO',
                'db_table': 'cmo_efetivo_lancamento',
                'ordering': ['lancado', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CMOEfetivoLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidade', models.CharField(choices=[('conformidade', 'Conformidade de Efetivo'), ('cobertura', 'Cobertura'), ('troca', 'Troca de Serviço'), ('lancamento', 'Lançamento CMO')], max_length=20)),
                ('registro_id', models.CharField(db_index=True, max_length=36)),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('valor_anterior', models.JSONField(blank=True, default=dict)),
                ('valor_novo', models.JSONField(blank=True, default=dict)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria (CMO Efetivo)',
                'verbose_name_plural': 'Logs de Auditoria (CMO Efetivo)',
                'db_table': 'cmo_efetivo_log',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='CMOEfetivoTroca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(db_index=True, max_length=255, verbose_name='Cliente')),
                ('grupo_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Cliente')),
                ('cr', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CR')),
                ('tipo_servico_nome', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Tipo de Serviço')),
                ('colaborador_atual', models.CharField(max_length=255, verbose_name='Colaborador Atual')),
                ('colaborador_substituto', models.CharField(max_length=255, verbose_name='Colaborador Substituto')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_troca', models.DateField(db_index=True, verbose_name='Data da Troca')),
                ('status_cmo', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], db_index=True, default='pendente', max_length=20, verbose_name='Status (CMO)')),
                ('observacao_cmo', models.TextField(blank=True, null=True, verbose_name='Observação da CMO')),
                ('conflito_detectado', models.BooleanField(default=False, verbose_name='Conflito detectado ao solicitar?')),
                ('conflito_justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa do conflito')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado', models.BooleanField(db_index=True, default=False)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_efetivo_decididas', to=settings.AUTH_USER_MODEL)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_efetivo_canceladas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_efetivo_criadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trocas_efetivo_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Troca de Serviço (Efetivo)',
                'verbose_name_plural': 'Trocas de Serviço (Efetivo)',
                'db_table': 'cmo_efetivo_troca',
                'ordering': ['-data_troca', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='cmoefetivoconformidade',
            index=models.Index(fields=['cr', 'data_referencia'], name='cmo_ef_conf_cr_data_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivoconformidade',
            index=models.Index(fields=['status_efetivo'], name='cmo_ef_conf_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivoconformidade',
            index=models.Index(fields=['status_lancamento'], name='cmo_ef_conf_lanc_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivocobertura',
            index=models.Index(fields=['cr', 'data_cobertura'], name='cmo_ef_cob_cr_data_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivocobertura',
            index=models.Index(fields=['status'], name='cmo_ef_cob_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivolancamento',
            index=models.Index(fields=['lancado'], name='cmo_ef_lanc_lancado_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivolancamento',
            index=models.Index(fields=['ocorrencia_tipo', 'ocorrencia_id'], name='cmo_ef_lanc_origem_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivolog',
            index=models.Index(fields=['entidade', 'registro_id'], name='cmo_ef_log_entidade_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivotroca',
            index=models.Index(fields=['cr', 'status_cmo'], name='cmo_ef_troca_cr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cmoefetivotroca',
            index=models.Index(fields=['cliente_nome', 'colaborador_atual', 'data_troca'], name='cmo_ef_troca_conflito_idx'),
        ),
    ]
