# Generated by Django 5.2.4 on 2026-07-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0058_cmo_efetivo_seed_tipos_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmoefetivocobertura',
            name='tipo_servico_nome',
            field=models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('alimentacao', 'Alimentação'), ('logistica', 'Logística'), ('seguranca', 'Segurança')], db_index=True, max_length=20, null=True, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='cmoefetivoconformidade',
            name='tipo_servico_nome',
            field=models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('alimentacao', 'Alimentação'), ('logistica', 'Logística'), ('seguranca', 'Segurança')], db_index=True, max_length=20, null=True, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='cmoefetivotroca',
            name='tipo_servico_nome',
            field=models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('alimentacao', 'Alimentação'), ('logistica', 'Logística'), ('seguranca', 'Segurança')], db_index=True, max_length=20, null=True, verbose_name='Tipo de Serviço'),
        ),
    ]
