# Generated by Django 5.2.4 on 2026-07-09 18:21
#
# Desfaz o efeito colateral da migration 0058: ela semeou "Limpeza",
# "Manutenção", "Alimentação", "Logística" e "Segurança" no catálogo
# TipoServico do Planner (model compartilhado), poluindo o dropdown de
# categorias do Planner com valores que na verdade eram só pro CMO Efetivo
# (que agora usa uma lista fixa própria, CMO_EFETIVO_TIPO_SERVICO_CHOICES,
# desacoplada do TipoServico -- ver models.py). Aqui só desativa (não
# exclui) essas 5 linhas específicas, para elas sumirem dos dropdowns
# ativos do Planner sem quebrar nenhum PlannerProject que porventura já as
# esteja referenciando.

from django.db import migrations

NOMES_A_DESATIVAR = [
    "Limpeza",
    "Manutenção",
    "Alimentação",
    "Logística",
    "Segurança",
]


def desativar(apps, schema_editor):
    TipoServico = apps.get_model('Gestao_a_Vista', 'TipoServico')
    db_alias = schema_editor.connection.alias
    TipoServico.objects.using(db_alias).filter(nome__in=NOMES_A_DESATIVAR).update(ativo=False)


def reativar(apps, schema_editor):
    TipoServico = apps.get_model('Gestao_a_Vista', 'TipoServico')
    db_alias = schema_editor.connection.alias
    TipoServico.objects.using(db_alias).filter(nome__in=NOMES_A_DESATIVAR).update(ativo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0059_cmo_efetivo_tipo_servico_choices'),
    ]

    operations = [
        migrations.RunPython(desativar, reativar),
    ]
