# Generated by Django 5.2.4 on 2026-07-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0060_cmo_efetivo_desfaz_poluicao_tiposervico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMOPonto',
        ),
        migrations.DeleteModel(
            name='CMOTrocaServico',
        ),
    ]
