# Generated by Django 5.2.4 on 2026-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0061_remove_cmo_mobile_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_codigo', models.CharField(db_index=True, max_length=50)),
                ('filial_codigo', models.CharField(blank=True, default='', max_length=50)),
                ('empresa_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa SRA',
                'verbose_name_plural': 'Empresas SRA',
                'db_table': 'Gestao_a_Vista_empresasra',
                'constraints': [models.UniqueConstraint(fields=('empresa_codigo', 'filial_codigo'), name='unique_empresasra_empresa_filial')],
            },
        ),
    ]
