# Generated by Django 5.2.4 on 2026-07-14 15:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0061_remove_cmo_mobile_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmoefetivoconformidade',
            name='status_efetivo',
            field=models.CharField(choices=[('aguardando_confirmacao', 'Aguardando Confirmação'), ('conforme', 'Conforme'), ('nao_conforme', 'Não Conforme')], default='aguardando_confirmacao', max_length=25, verbose_name='Status do Efetivo'),
        ),
        migrations.AlterField(
            model_name='cmoefetivolog',
            name='entidade',
            field=models.CharField(choices=[('conformidade', 'Conformidade de Efetivo'), ('cobertura', 'Cobertura'), ('troca', 'Troca de Serviço'), ('lancamento', 'Lançamento CMO'), ('movimentacao', 'Registro de Movimentação')], max_length=20),
        ),
        migrations.CreateModel(
            name='CMOEfetivoRegistroMovimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(db_index=True, max_length=255, verbose_name='Cliente')),
                ('cr', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='CR')),
                ('tipo_servico_nome', models.CharField(blank=True, choices=[('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('alimentacao', 'Alimentação'), ('logistica', 'Logística'), ('seguranca', 'Segurança')], max_length=20, null=True, verbose_name='Tipo de Serviço')),
                ('data_referencia', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Data de Referência')),
                ('gerente', models.CharField(blank=True, max_length=255, verbose_name='Gerente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('posto', models.CharField(blank=True, max_length=150, verbose_name='Posto')),
                ('posto_cr', models.CharField(blank=True, max_length=100, verbose_name='Posto CR')),
                ('horario', models.CharField(blank=True, max_length=50, verbose_name='Horário')),
                ('intervalo', models.CharField(blank=True, max_length=50, verbose_name='Intervalo')),
                ('cobertura', models.CharField(blank=True, max_length=255, verbose_name='Cobertura')),
                ('cargo_cobertura', models.CharField(blank=True, max_length=150, verbose_name='Cargo (Cobertura)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('situacao', models.CharField(choices=[('falta', 'Falta'), ('folga', 'Folga'), ('servico_extra', 'Serviço Extra'), ('remanejamento', 'Remanejamento'), ('ferias', 'Férias'), ('atraso', 'Atraso'), ('posto', 'Posto')], max_length=20, verbose_name='Situação')),
                ('situacao_cobertura', models.CharField(blank=True, choices=[('servico_normal', 'Serviço Normal'), ('dobra_extra', 'Fazendo Dobra/Extra'), ('extra_entrada', 'Extra Entrada'), ('extra_saida', 'Extra Saída')], max_length=20, null=True, verbose_name='Situação da Cobertura')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conformidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_movimentacao', to='Gestao_a_Vista.cmoefetivoconformidade', verbose_name='Conformidade de Origem')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_movimentacao_cmo_efetivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Movimentação (CMO)',
                'verbose_name_plural': 'Registros de Movimentação (CMO)',
                'db_table': 'cmo_efetivo_registro_movimentacao',
                'ordering': ['-data_referencia', '-criado_em'],
                'indexes': [models.Index(fields=['cr', 'data_referencia'], name='cmo_ef_mov_cr_data_idx')],
            },
        ),
    ]
