# Generated by Django 5.2.4 on 2026-07-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0062_empresasra'),
        ('Gestao_a_Vista', '0063_cmo_efetivo_registro_movimentacao'),
    ]

    operations = [
    ]
