# Generated by Django 5.2.4 on 2026-07-15 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0064_merge_empresasra_e_cmo_registro_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImportante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_importantes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Importante',
                'verbose_name_plural': 'Links Importantes',
                'db_table': 'links_importantes',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
