# Generated by Django 5.2.4 on 2026-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestao_a_Vista', '0066_links_importantes_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tutorial_visto',
            field=models.BooleanField(default=False, verbose_name='Já viu o tutorial de primeiro acesso?'),
        ),
    ]
